[package]
name = "borsh-helper"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "serialize-borsh"
path = "serialize_borsh.rs"

[dependencies]
near-sdk = "5.11.0"
near-crypto = "0.29.2"
borsh = "1.5.7"
base64 = "0.22.1"
clap = { version = "4.5", features = ["derive"] }