[package]
name = "onsocialrelayer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "5.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
borsh = "1.5.5"
ed25519-dalek = "2"

[dev-dependencies]
near-sdk = { version = "5.11.0", features = ["unit-testing"] }
cargo-near = "0.13.4"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true