[package]
name = "onsocialrelayer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { version = "=5.0.0", features = ["legacy", "unit-testing"] }
near-gas = "0.3.0"
borsh = "1.5.5"
borsh-derive = "1.5.5"